# Generated by Django 3.1.5 on 2021-01-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210108_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='defaullt', max_length=50),
            preserve_default=False,
        ),
    ]
