# Generated by Django 3.1.5 on 2021-01-10 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatmsg',
            name='PC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg', to='chat.privatechat'),
        ),
    ]
